# Generated by Django 3.1.14 on 2023-01-29 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_text2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='text2',
        ),
    ]
